apiVersion: v1
kind: Service
metadata:
  name: {{ include "quakewatch.fullname" . }}
  labels:
    app: {{ include "quakewatch.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "quakewatch.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
