replicaCount: 3

image:
  repository: michalreuven/quakewatch
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: 30080

env:
  appEnv: "prod"

secret:
  apiKey: "CHANGE_ME"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

cronjob:
  enabled: true
  schedule: "*/5 * * * *"

serviceAccount:
  create: false
  name: ""
